[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-Wl,-rpath,/usr/lib/swift",
]

[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-arg=-Wl,-rpath,/usr/lib/swift",
]

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
